my_joint_position_controller:
    type: franka_example_controllers/MyJointPositionController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

my_cartesian_pose_controller:
    type: franka_example_controllers/MyCartesianPoseController
    arm_id: panda

exucobot_cartesian_velocity_controller:
    type: franka_example_controllers/ExuCobotCartesianVelocityController
    arm_id: panda

exucobot_cartesian_impedance_controller:
    type: franka_example_controllers/ExuCobotCartesianImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7